apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-app-blue
  labels: { app: aceest-gym, env: blue }
spec:
  replicas: 2
  selector:
    matchLabels: { app: aceest-gym, env: blue }
  template:
    metadata:
      labels: { app: aceest-gym, env: blue }
    spec:
      containers:
      - name: aceest-app
        image: 2024tm93169/aceest-fitness-gym:1.2
        ports: [ { containerPort: 5000 } ]
