apiVersion: v1
kind: Service
metadata:
  name: aceest-gym-service
spec:
  type: ClusterIP
  selector:
    app: aceest-gym
    env: blue   # switch to 'green' to cut over
  ports:
  - port: 80
    targetPort: 5000
