apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-app-va
  labels: { app: aceest-gym, version: vA }
spec:
  replicas: 2
  selector:
    matchLabels: { app: aceest-gym, version: vA }
  template:
    metadata:
      labels: { app: aceest-gym, version: vA }
    spec:
      containers:
      - name: aceest-app
        image: 2024tm93169/aceest-fitness-gym:1.3
        ports: [ { containerPort: 5000 } ]
