apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aceest-canary-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  ingressClassName: nginx
  rules:
  - host: aceest.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aceest-stable-svc
            port: { number: 80 }
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aceest-canary-svc
            port: { number: 80 }
