apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-app-stable
  labels: { app: aceest-gym, version: stable }
spec:
  replicas: 4
  selector:
    matchLabels: { app: aceest-gym, version: stable }
  template:
    metadata:
      labels: { app: aceest-gym, version: stable }
    spec:
      containers:
      - name: aceest-app
        image: 2024tm93169/aceest-fitness-gym:1.2.2
        ports: [ { containerPort: 5000 } ]
